name: barbershop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#11-05-2025 0.0.1+1
version: 0.0.1+1

environment:
  sdk: ">=3.0.0  <3.27.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  vector_graphics: ^1.1.18
  pinput: ^5.0.1
  smart_auth: 3.1.0
  mask_text_input_formatter: ^2.9.0
  dio: ^5.6.0
  get_it: ^8.0.0
  shared_preferences: ^2.5.2
  talker_dio_logger: ^4.6.13
  cached_network_image: ^3.4.1
  table_calendar: ^3.2.0
  dotted_line: ^3.2.3
  geolocator: 13.0.1
  geolocator_android: 4.6.0
  geolocator_apple: 2.3.8
  shimmer: ^3.0.0
  keyboard_dismisser: ^3.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.9.0
  flutter_launcher_icons: ^0.13.1
#  flutter_native_splash: ^2.4.6


  flutter_lints: ^4.0.0
  build_runner: ^2.4.10

flutter_gen:
  output: lib/core/gen/ # Optional (default: lib/gen/)

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:


  assets:
    - assets/icon/
    - assets/img/
    - assets/lottie/
#    - assets/splash/
  uses-material-design: true
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/ios-app-icon.png"
  image_path_android: "assets/icon/android-app-icon.png"
  adaptive_icon_background: "assets/icon/android-app-icon-background.png"
  adaptive_icon_foreground: "assets/icon/android-app-icon-foreground.png"
  remove_alpha_ios: true


#flutter_native_splash:
#  color: "#053827"                # Background color
#  image: assets/splash/splash.png  # Your new splash icon/image
#  android: true
#  ios: true
#  android_gravity: center
